//
export const GET_DETAILS_LOADING_ED = "GET_DETAILS_LOADING_ED";
export const GET_DETAILS_SUCCESS_ED = "GET_DETAILS_SUCCESS_ED";
export const GET_DETAILS_ERROR_ED = "GET_DETAILS_ERROR_ED";
//
export const ADD_DETAILS_LOADING_ED = "ADD_DETAILS_LOADING_ED";
export const ADD_DETAILS_SUCCESS_ED = "ADD_DETAILS_SUCCESS_ED";
export const ADD_DETAILS_ERROR_ED = "ADD_DETAILS_ERROR_ED";
//
export const UPDATE_DETAILS_LOADING_ED = "UPDATE_DETAILS_LOADING_ED";
export const UPDATE_DETAILS_SUCCESS_ED = "UPDATE_DETAILS_SUCCESS_ED";
export const UPDATE_DETAILS_ERROR_ED = "UPDATE_DETAILS_ERROR_ED";

//
export const DELETE_DETAILS_LOADING_ED = "DELETE_DETAILS_LOADING_ED";
export const DELETE_DETAILS_SUCCESS_ED = "DELETE_DETAILS_SUCCESS_ED";
export const DELETE_DETAILS_ERROR_ED = "DELETE_DETAILS_ERROR_ED";
