//
export const GET_DETAILS_LOADING = "GET_DETAILS_LOADING";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const GET_DETAILS_ERROR = "GET_DETAILS_ERROR";
//
export const ADD_DETAILS_LOADING = "ADD_DETAILS_LOADING";
export const ADD_DETAILS_SUCCESS = "ADD_DETAILS_SUCCESS";
export const ADD_DETAILS_ERROR = "ADD_DETAILS_ERROR";
//
export const UPDATE_DETAILS_LOADING = "UPDATE_DETAILS_LOADING";
export const UPDATE_DETAILS_SUCCESS = "UPDATE_DETAILS_SUCCESS";
export const UPDATE_DETAILS_ERROR = "UPDATE_DETAILS_ERROR";
//
export const DELETE_DETAILS_LOADING = "DELETE_DETAILS_LOADING";
export const DELETE_DETAILS_SUCCESS = "DELETE_DETAILS_SUCCESS";
export const DELETE_DETAILS_ERROR = "DELETE_DETAILS_ERROR";
